name: Build and Deploy Strapi to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configure AWS credentials (needed only for Terraform / ECS)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3. Login to Docker Hub (PUBLIC REGISTRY)
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # 4. Build and Push Strapi Docker Image
      - name: Build and Push Docker Image
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/jaspal-strapi:${{ github.sha }}
          docker build -t $IMAGE ./backend
          docker push $IMAGE
          echo "IMAGE_URL=$IMAGE" >> $GITHUB_ENV

      # 5. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # 6. Terraform Init & Apply
      - name: Terraform Apply
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve \
            -var="image_url=${IMAGE_URL}" \
            -var="db_password=dummy"
